TrueCircle is a project born from empathy—using AI to explore and understand the depth of human relationships. It’s not just code; it’s connection.
Tier	Monthly	Perks
Circle Ally	$5	Shout-out on README
Circle Builder	$20	Early access to features
Circle Visionary	$50+	Strategy calls, co-creation invites
“This project is built with heart, not hype. If you believe in the power of meaningful tech, I’d be honored to have you in the circle.”
github: surendgrover  
patreon: truecircle             
open_collective: truecircle     
buy_me_a_coffee: surendragra