blank_issues_enabled: true
contact_links:
  - name: ЁЯУЪ Documentation / рдкреНрд░рд▓реЗрдЦрди
    url: https://github.com/surendragrover/Truecircle/blob/main/TrueCircle_Complete_Documentation.md
    about: рдкреВрд░реНрдг рдкреНрд░реЛрдЬреЗрдХреНрдЯ рдбреЙрдХреНрдпреВрдореЗрдВрдЯреЗрд╢рди рдкрдврд╝реЗрдВ / Read complete project documentation
  - name: ЁЯТм Discussions / рдЪрд░реНрдЪрд╛
    url: https://github.com/surendragrover/Truecircle/discussions
    about: рд╕рд╛рдорд╛рдиреНрдп рдЪрд░реНрдЪрд╛ рдФрд░ рд╕рд╡рд╛рд▓ / General discussions and questions
  - name: ЁЯФТ Privacy Guide / рдкреНрд░рд╛рдЗрд╡реЗрд╕реА рдЧрд╛рдЗрдб
    url: https://github.com/surendragrover/Truecircle/blob/main/PRIVACY_DEMO_MODE_GUIDE.md
    about: Privacy Mode рдФрд░ demo data рдЧрд╛рдЗрдб / Privacy Mode and demo data guide
