// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:239213685086:web:7931d023b10d0a2f1107cf',
    messagingSenderId: '239213685086',
    projectId: 'truecircle-dbcdb',
    authDomain: 'truecircle-dbcdb.firebaseapp.com',
    storageBucket: 'truecircle-dbcdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:239213685086:android:f25587f9c1c2b5df1107cf',
    messagingSenderId: '239213685086',
    projectId: 'truecircle-dbcdb',
    storageBucket: 'truecircle-dbcdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:239213685086:ios:0b5d86c4a18002431107cf',
    messagingSenderId: '239213685086',
    projectId: 'truecircle-dbcdb',
    storageBucket: 'truecircle-dbcdb.appspot.com',
    iosBundleId: 'com.example.truecircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:239213685086:ios:7ba4ca3e2a12b93c1107cf',
    messagingSenderId: '239213685086',
    projectId: 'truecircle-dbcdb',
    storageBucket: 'truecircle-dbcdb.appspot.com',
    iosBundleId: 'com.example.truecircle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:239213685086:web:574d0a030dd34a651107cf',
    messagingSenderId: '239213685086',
    projectId: 'truecircle-dbcdb',
  );
}
