// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
class DefaultFirebaseOptions {
  // NOTE: Keys provided explicitly by user. For production, consider moving
  // sensitive API keys to env / remote config if policy requires.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        // No linux config supplied; reuse web (Firestore REST works) or throw.
        return web;
      default:
        return web;
    }
  }

  // Provided web config (includes measurementId)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLImMOVbgX1LFyqREMSyiQZyY_XUtwH98',
    appId: '1:239213685086:web:7931d023b10d0a2f1107cf',
    messagingSenderId: '239213685086',
    projectId: 'truecircle-dbcdb',
    authDomain: 'truecircle-dbcdb.firebaseapp.com',
    storageBucket: 'truecircle-dbcdb.firebasestorage.app',
    measurementId: 'G-JJ3V7PTVXB',
  );

  // Android entry for applicationId com.truecircle.app
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnC1scF347y4tDDZ7PIHZQ1R7UqIh6mTM',
    appId: '1:239213685086:android:a6da963df7a50da61107cf',
    messagingSenderId: '239213685086',
    projectId: 'truecircle-dbcdb',
    storageBucket: 'truecircle-dbcdb.firebasestorage.app',
  );

  // iOS/macOS/windows not yet configured – fallback to web credentials for read-only usage.
  static const FirebaseOptions ios = web;
  static const FirebaseOptions macos = web;
  static const FirebaseOptions windows = web;
}